"""
Revision ID: 0003_add_token_tracking_tables
Revises: 0002_add_refresh_tokens
Create Date: 2026-02-23 22:36:00.000000
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0003_add_token_tracking_tables"
down_revision = "0002_add_refresh_tokens"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("deepgram_seconds", sa.Float(), nullable=True, server_default="0"),
        sa.Column("deepl_characters", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("total_requests", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "period", name="uq_user_period"),
    )
    op.create_index(op.f("ix_token_usage_id"), "token_usage", ["id"], unique=False)
    op.create_index(
        op.f("ix_token_usage_user_id"), "token_usage", ["user_id"], unique=False
    )

    op.create_table(
        "token_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_token_events_event_id"), "token_events", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_events_user_id"), "token_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_events_user_id"), table_name="token_events")
    op.drop_index(op.f("ix_token_events_event_id"), table_name="token_events")
    op.drop_table("token_events")
    op.drop_index(op.f("ix_token_usage_user_id"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_id"), table_name="token_usage")
    op.drop_table("token_usage")
    # ### end Alembic commands ###
