"""
Revision ID: 0004_add_user_settings_table
Revises: 0003_add_token_tracking_tables
Create Date: 2026-02-24 12:20:00.000000
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0004_add_user_settings_table"
down_revision = "0003_add_token_tracking_tables"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "microphone_enabled", sa.Boolean(), nullable=True, server_default="true"
        ),
        sa.Column(
            "tab_audio_enabled", sa.Boolean(), nullable=True, server_default="true"
        ),
        sa.Column(
            "original_language",
            sa.String(length=10),
            nullable=True,
            server_default="'RU'",
        ),
        sa.Column(
            "translation_language",
            sa.String(length=10),
            nullable=True,
            server_default="'EN'",
        ),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_settings_id"), "user_settings", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.drop_index(op.f("ix_user_settings_id"), table_name="user_settings")
    op.drop_table("user_settings")
    # ### end Alembic commands ###
